In [1]:
import pandas as pd

## Reading Data

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head()

fever  bodyPain  age  ruunyNose  diffBreath  infectionProb
0    100         1   74          1          -1              1
1    100         0   26          0           1              0
2    100         1   36          0           0              0
3    102         1   91          1          -1              1
4    100         0   84          0          -1              1

In [4]:
df.tail()

fever  bodyPain  age  ruunyNose  diffBreath  infectionProb
2494     98         0   95          1           1              1
2495    101         0   91          0          -1              0
2496    101         1   39          0           0              1
2497     98         1   13          0          -1              1
2498    101         0   94          0           0              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fever          2499 non-null   int64
 1   bodyPain       2499 non-null   int64
 2   age            2499 non-null   int64
 3   ruunyNose      2499 non-null   int64
 4   diffBreath     2499 non-null   int64
 5   infectionProb  2499 non-null   int64
dtypes: int64(6)
memory usage: 117.3 KB


In [6]:
df['fever'].value_counts()

104    391
99     377
98     371
103    351
100    351
101    340
102    318
Name: fever, dtype: int64

In [7]:
df['diffBreath'].value_counts()

-1    857
 0    825
 1    817
Name: diffBreath, dtype: int64

In [8]:
df.describe()

fever     bodyPain          age    ruunyNose   diffBreath  \
count  2499.000000  2499.000000  2499.000000  2499.000000  2499.000000   
mean    100.989996     0.494998    50.489396     0.488996    -0.016006   
std       2.044222     0.500075    29.007622     0.499979     0.818462   
min      98.000000     0.000000     1.000000     0.000000    -1.000000   
25%      99.000000     0.000000    25.500000     0.000000    -1.000000   
50%     101.000000     0.000000    50.000000     0.000000     0.000000   
75%     103.000000     1.000000    76.000000     1.000000     1.000000   
max     104.000000     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2499.000000  
mean        0.482993  
std         0.499811  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

## Train Test Spliting

In [9]:
import numpy as np

In [10]:
np.random.permutation(7) ## It gives a random array of the the length of the data

array([2, 0, 3, 1, 4, 5, 6])

In [11]:
## produces random shuffeld numberss
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]


In [12]:
train,test = data_split(df,0.2)

In [13]:
train

fever  bodyPain  age  ruunyNose  diffBreath  infectionProb
461     103         1   68          1          -1              1
109     102         0   36          0           1              1
2296    101         0   72          1          -1              0
354     103         0   26          0           0              0
266      98         0   70          1          -1              1
...     ...       ...  ...        ...         ...            ...
1638    100         1   31          0          -1              1
1095     99         0   15          0           0              0
1130    104         0    7          1          -1              0
1294    102         1   43          0          -1              0
860      98         0   40          1           1              1

[2000 rows x 6 columns]

In [14]:
test

fever  bodyPain  age  ruunyNose  diffBreath  infectionProb
2319    101         1   36          0          -1              1
1865    100         1   19          0           0              1
902     104         1   31          0          -1              0
2240     99         1   68          1           1              0
1285    104         1   53          1           0              0
...     ...       ...  ...        ...         ...            ...
1037    103         1   78          0           1              0
2054     99         0   79          1           0              0
1860    100         0    6          1          -1              0
1862    104         1   31          0           0              1
1151     99         0   15          0           0              0

[499 rows x 6 columns]

In [15]:
X_train = train[['fever','bodyPain','age','ruunyNose','diffBreath']]

In [16]:
X_train

fever  bodyPain  age  ruunyNose  diffBreath
461     103         1   68          1          -1
109     102         0   36          0           1
2296    101         0   72          1          -1
354     103         0   26          0           0
266      98         0   70          1          -1
...     ...       ...  ...        ...         ...
1638    100         1   31          0          -1
1095     99         0   15          0           0
1130    104         0    7          1          -1
1294    102         1   43          0          -1
860      98         0   40          1           1

[2000 rows x 5 columns]

In [17]:
X_train = X_train.to_numpy()

In [18]:
X_train

array([[103,   1,  68,   1,  -1],
       [102,   0,  36,   0,   1],
       [101,   0,  72,   1,  -1],
       ...,
       [104,   0,   7,   1,  -1],
       [102,   1,  43,   0,  -1],
       [ 98,   0,  40,   1,   1]], dtype=int64)

In [19]:
# Similar to X train data we use the Xtest
X_test = test[['fever','bodyPain','age','ruunyNose','diffBreath']].to_numpy()

In [20]:
#Y test for tes and train
Y_train = train[['infectionProb']].to_numpy().reshape(2000,)     #reshape(1,-1)
Y_test = test[['infectionProb']].to_numpy().reshape(499,)


In [21]:
Y_train

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

## Sk learn has many models we user the logistic regresssion

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
clf = LogisticRegression()
clf.fit(X_train,Y_train)


LogisticRegression()

In [24]:
clf.predict([[103,0,62,1,1]])  #it predicts..

array([1], dtype=int64)

In [25]:
clf.predict_proba([[102,1,12,-1,0]])  # this modal will give  the probabilty of the modal

array([[0.50494265, 0.49505735]])

In [26]:
input_features = [102,1,12,-1,0]  # this gives the probablity of % getting the percentage
clf.predict_proba([input_features])[0][1]

0.4950573482976671